### ISSUE TITLE
is this tool safe

### ISSUE THREAD

**Issue by aeugurauhhr** [ate47/atian-cod-tools#1]
Hello! Is this tool safe? A couple of weeks ago my Gmail got hacked by people from the East, and nearly lost all my accounts but recovered all of them after. Now to be fair I did see that I had compromised passwords in my Google account before the hacking but I just wanna make sure that this, and the Cold War DLL and game download from the Donetsk Discord server are safe.

So are they all safe?

**Comment by aeugurauhhr** [comment]
I know, I know... It might sound stupid because I'm most likely gonna get the answer "Yes, this tool is safe", but I still want to make sure in case another hacking could happen again.

**Comment by ate47** [comment]
Hello, like you said, I can't be trusted because it's my repository. If you want to check the whole repository to search for a hack you can (Everything is compiled by github, so I can't inject anything more)

But it is probable that your antivirus or Windows defender complain about it, nothing is signed.

For the Donetsk DLLs, in my opinion they are too stupid to be able to do that, but I can't tell.

On another perspective, if you're not using a dll to get offline, it might be possible to get a ban from Activision. At least some people got that. (not me)

**Comment by aeugurauhhr** [comment]
Thank you for replying. I might as well risk it one more time because my passwords were already compromised prior to me discovering I could get this game for "free".

**Comment by ate47** [comment]
I was about to close it. You won by few seconds lol
